{
  "schema_version": "1.4.0",
  "id": "GHSA-cqhg-xjhh-p8hf",
  "modified": "2023-02-28T15:12:16Z",
  "published": "2020-07-27T21:52:43Z",
  "aliases": [
    "CVE-2020-10177"
  ],
  "summary": "Out-of-bounds reads in Pillow",
  "details": "Pillow before 6.2.3 and 7.x before 7.0.1 has multiple out-of-bounds reads in libImaging/FliDecode.c.",
  "severity": [
    {
      "type": "CVSS_V3",
      "score": "CVSS:3.1/AV:L/AC:L/PR:N/UI:R/S:U/C:H/I:N/A:N"
    }
  ],
  "affected": [
    {
      "package": {
        "ecosystem": "PyPI",
        "name": "Pillow"
      },
      "ranges": [
        {
          "type": "ECOSYSTEM",
          "events": [
            {
              "introduced": "0"
            },
            {
              "fixed": "7.1.0"
            }
          ]
        }
      ]
    }
  ],
  "references": [
    {
      "type": "ADVISORY",
      "url": "https://nvd.nist.gov/vuln/detail/CVE-2020-10177"
    },
    {
      "type": "WEB",
      "url": "https://github.com/python-pillow/Pillow/pull/4503"
    },
    {
      "type": "WEB",
      "url": "https://github.com/python-pillow/Pillow/pull/4538"
    },
    {
      "type": "PACKAGE",
      "url": "https://github.com/python-pillow/Pillow"
    },
    {
      "type": "WEB",
      "url": "https://github.com/python-pillow/Pillow/commits/master/src/libImaging"
    },
    {
      "type": "WEB",
      "url": "https://lists.debian.org/debian-lts-announce/2020/08/msg00012.html"
    },
    {
      "type": "WEB",
      "url": "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/BEBCPE4F2VHTIT6EZA2YZQZLPVDEBJGD/"
    },
    {
      "type": "WEB",
      "url": "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/HOKHNWV2VS5GESY7IBD237E7C6T3I427/"
    },
    {
      "type": "WEB",
      "url": "https://pillow.readthedocs.io/en/stable/releasenotes/6.2.3.html"
    },
    {
      "type": "WEB",
      "url": "https://pillow.readthedocs.io/en/stable/releasenotes/7.1.0.html"
    },
    {
      "type": "WEB",
      "url": "https://snyk.io/vuln/SNYK-PYTHON-PILLOW-574573"
    },
    {
      "type": "WEB",
      "url": "https://usn.ubuntu.com/4430-1/"
    },
    {
      "type": "WEB",
      "url": "https://usn.ubuntu.com/4430-2/"
    }
  ],
  "database_specific": {
    "cwe_ids": [
      "CWE-125"
    ],
    "severity": "MODERATE",
    "github_reviewed": true,
    "github_reviewed_at": "2020-07-27T21:52:00Z",
    "nvd_published_at": "2020-06-25T19:15:00Z"
  }
}