{
  "schema_version": "1.4.0",
  "id": "GHSA-24wv-mv5m-xv4h",
  "modified": "2023-03-27T21:31:45Z",
  "published": "2023-03-26T21:30:23Z",
  "aliases": [
    "CVE-2023-28858"
  ],
  "summary": "redis-py Race Condition vulnerability",
  "details": "redis-py before 4.5.3, as used in ChatGPT and other products, leaves a connection open after canceling an async Redis command at an inopportune time (in the case of a pipeline operation), and can send response data to the client of an unrelated request in an off-by-one manner. The fixed versions for this CVE Record are 4.3.6, 4.4.3, and 4.5.3, but [are believed to be incomplete](https://github.com/redis/redis-py/issues/2665). CVE-2023-28859 has been assigned the issues caused by the incomplete fixes.",
  "severity": [

  ],
  "affected": [
    {
      "package": {
        "ecosystem": "PyPI",
        "name": "redis"
      },
      "ranges": [
        {
          "type": "ECOSYSTEM",
          "events": [
            {
              "introduced": "0"
            },
            {
              "fixed": "4.3.6"
            }
          ]
        }
      ]
    },
    {
      "package": {
        "ecosystem": "PyPI",
        "name": "redis"
      },
      "ranges": [
        {
          "type": "ECOSYSTEM",
          "events": [
            {
              "introduced": "4.4.0"
            },
            {
              "fixed": "4.4.3"
            }
          ]
        }
      ]
    },
    {
      "package": {
        "ecosystem": "PyPI",
        "name": "redis"
      },
      "ranges": [
        {
          "type": "ECOSYSTEM",
          "events": [
            {
              "introduced": "4.5.0"
            },
            {
              "fixed": "4.5.3"
            }
          ]
        }
      ]
    }
  ],
  "references": [
    {
      "type": "ADVISORY",
      "url": "https://nvd.nist.gov/vuln/detail/CVE-2023-28858"
    },
    {
      "type": "WEB",
      "url": "https://github.com/redis/redis-py/issues/2624"
    },
    {
      "type": "WEB",
      "url": "https://github.com/redis/redis-py/pull/2641"
    },
    {
      "type": "PACKAGE",
      "url": "https://github.com/redis/redis-py"
    },
    {
      "type": "WEB",
      "url": "https://github.com/redis/redis-py/compare/v4.3.5...v4.3.6"
    },
    {
      "type": "WEB",
      "url": "https://github.com/redis/redis-py/compare/v4.4.2...v4.4.3"
    },
    {
      "type": "WEB",
      "url": "https://github.com/redis/redis-py/compare/v4.5.2...v4.5.3"
    },
    {
      "type": "WEB",
      "url": "https://github.com/redis/redis-py/releases/tag/v4.4.4"
    },
    {
      "type": "WEB",
      "url": "https://github.com/redis/redis-py/releases/tag/v4.5.4"
    },
    {
      "type": "WEB",
      "url": "https://openai.com/blog/march-20-chatgpt-outage"
    }
  ],
  "database_specific": {
    "cwe_ids": [

    ],
    "severity": "HIGH",
    "github_reviewed": true,
    "github_reviewed_at": "2023-03-27T21:31:45Z",
    "nvd_published_at": "2023-03-26T19:15:00Z"
  }
}